name: lint

on:

  pull_request:
    paths:
      - "webserver/**"
      - ".github/workflows/clippy-fmt.yml"
    types: [opened, synchronize, reopened]

jobs:

  clippy:
    name: clippy check
    runs-on: ubuntu-latest

    env:
      CI: 1
      CARGO_INCREMENTAL: false

    steps:
      - uses: actions/checkout@v4
#
#      - name: Install Rust
#        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
#        with:
#          toolchain: stable
#          components: clippy

      - name: clippy
        timeout-minutes: 30
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-check"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace --all-features --tests

  setup-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Compose
        run: cd webserver && docker compose up -d

      - name: Run Tests
        run: cd webserver && cargo test --verbose