name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  clippy:
    name: clippy check
    runs-on: ubuntu-latest

    env:
      CI: 1
      CARGO_INCREMENTAL: false

    steps:
      - uses: actions/checkout@v4
#
#      - name: Install Rust
#        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
#        with:
#          toolchain: stable
#          components: clippy

      - name: clippy
        timeout-minutes: 30
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-check"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace --all-features --tests
