name: Start PR preview app

on:
  pull_request:
    paths:
      - "webserver/**"
      - ".github/workflows/fly_pr-preview-develop.yml"
    branches:
      - develop
    types: [ labeled, synchronize, opened, reopened, closed ]

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  preview-app:
    #if: contains(github.event.pull_request.labels.*.name, 'PR preview app')
    name: Staging dev preview app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd webserver && flyctl deploy --app webserver-flowerwork-develop --remote-only --config fly-pr-preview.toml
