name: Rust CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "webserver/**"
      - ".github/workflows/rust.yml"
  pull_request:
    paths:
      - "webserver/**"
      - ".github/workflows/rust.yml"
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Database
        run: cd webserver && docker compose up -d

      - name: Run Tests
        run: cd webserver && cargo test --verbose
